# Generated by Django 3.2.18 on 2023-05-08 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attribute',
            field=models.CharField(default='Dark', max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='star',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
