# Generated by Django 3.2.19 on 2023-05-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_card_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='attribute',
        ),
    ]
