# Generated by Django 3.2.19 on 2023-05-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_card_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attribute',
            field=models.CharField(choices=[('Dark', 'Dark'), ('Earth', 'Earth'), ('Fire', 'Fire'), ('Light', 'Light'), ('Wind', 'Wind'), ('Divine', 'Divine')], default='Dark', max_length=6),
        ),
    ]
