# Generated by Django 3.2.19 on 2023-05-15 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_card_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attack',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='card',
            name='defense',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='attribute',
            field=models.CharField(choices=[('Dark', 'Dark'), ('Earth', 'Earth'), ('Fire', 'Fire'), ('Light', 'Light'), ('Wind', 'Wind'), ('Water', 'Water'), ('Divine', 'Divine')], default='Dark', max_length=6),
        ),
    ]
